### ISSUE TITLE
[TEMPLATE] SendGrid Emailer Sender

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/foundry#10]
## Description
This template is designed to send emails to customers using SendGrid's API. The customers/emails information is being pulled from a dummy database and can be integrated with any API into a table. It's built on top of Sendgrid's mail send endpoint, and allows users to edit sender fields (like the sender email and name), email text and subject, as well as CC and BCC fields.

### Integrations and features
A list of specific integrations, data sources, and specific features
 - Users/Customers Data (Dummy DB)
 - SendGrid API

#### Attachments
- [ Public Link ] (https://app.appsmith.com/app/sendgrid-send-emails/home-634efbf028546824aa24cf68)
- [JSON Export](https://github.com/appsmithorg/foundry/files/9818171/SendGrid.-.Send.Emails.json.zip)

##### Screenshots

<img width="1491" alt="sendgrid-mailer-1" src="https://user-images.githubusercontent.com/4999463/196640880-28052c10-60b3-47e9-ad18-77e4dc25c472.png">
<img width="1495" a
<img width="1519" alt="sendgrid-mailer-2" src="https://user-images.githubusercontent.com/4999463/196641431-6f42df94-a260-4409-b84b-8312777887e1.png">
<img width="1519" alt="sendgrid-mailer" src="https://user-images.githubusercontent.com/4999463/196640933-7d66f09a-747a-4b40-bee3-2451a021546a.png">

**Comment by rlnorthcutt** [comment]
Congratulations! You won a bronze prize for this submission and 4 coins for use in the swag store!
