### ISSUE TITLE
Unable to redeem from shop 

### ISSUE THREAD

**Issue by Chirag8023** [appsmithorg/foundry#12]
I currently have 4 coins in my account but I'm unable to redeem any item from shop on : https://app.appsmith.com/app/hacktoberfest-2022/shop-633619b89cb3ec2a8a933332

**Comment by rlnorthcutt** [comment]
@Chirag8023 the swag shop will not be open for redeeming coins until after Hacktoberfest and we have awarded all the prizes. 

In the mean time, feel free to submit as many template entries as you like! You can win multiple prizes.

**Comment by Chirag8023** [comment]
ok, thank you 🙏🏻

**Comment by rlnorthcutt** [comment]
thanks for the feedback - I added a note to the Swag Store for other people who may be wondering
