### ISSUE TITLE
[TEMPLATE] Olympics Dashboard built on top of Postgres

### ISSUE THREAD

**Issue by vihar-appsmith** [appsmithorg/foundry#13]
## Description

This app lets you analyze Olympics data, fork it and try it out.

### Integrations and features
- Postgres

#### Attachments
- [ ] **Link to app** - Link to the _public_ app
- [ ] **Screenshots** - Add one or more screenshots to help show your app.
- [ ] **JSON Export** - Attach the [JSON export](https://docs.appsmith.com/advanced-concepts/more/backup-restore#export-application) for your app to the issue.

Public link -- https://app.appsmith.com/app/olympics-dashboard/page1-6343de7205671e46ee8fb0bb

Screenshots -- 

<img width="1792" alt="CleanShot 2022-10-19 at 21 49 55@2x" src="https://user-images.githubusercontent.com/116192904/196748205-26501a54-6293-4136-b41f-9fa5d1223554.png">

Export file --

[Olympics Dashboard.json.zip](https://github.com/appsmithorg/foundry/files/9822361/Olympics.Dashboard.json.zip)

**Comment by rlnorthcutt** [comment]
thanks for submitting!
