### ISSUE TITLE
Video_Games

### ISSUE THREAD

**Issue by HarshitGupta3017** [appsmithorg/foundry#14]
## Description
A simple template for refreshing old vibes of video games.

### Integrations and features
A list of specific integrations, data sources, and specific features
 - database
 - an API
 - table with entries
 - form for updation

#### Attachments

- [x] **Link to app** - [Link to the _public_ app](https://app.appsmith.com/app/video-games/page1-635262c6dc264920d5e25995?branch=main)

- [x] **Screenshots** 
    - Data in the games table.
    
    ![image](https://user-images.githubusercontent.com/73373885/197170993-56011413-a243-4eb8-8c2d-2a32194402d8.png)

    - Current page is filtered according to the year of release.
   
    ![image](https://user-images.githubusercontent.com/73373885/197172333-8884b86a-04e4-445a-a86f-80018bb16a2b.png)

    - Updated entry.
 
    ![image](https://user-images.githubusercontent.com/73373885/197172813-0adff47b-6dd4-4aa0-9947-09b802614432.png)
    
    ![image](https://user-images.githubusercontent.com/73373885/197177409-6dffcc60-5410-4155-9879-cb383af553bf.png)

**Comment by rlnorthcutt** [comment]
Thank you for your submission. Unfortunately, you did not score high enough to win an award. But - please take part in our next event!
