### ISSUE TITLE
[TEMPLATE] Login interface powered by Appsmith

### ISSUE THREAD

**Issue by Chirag8023** [appsmithorg/foundry#15]
## Description
this is a working Login Interface showing functionality of entering username & password with submit button. This is purely designed to show UI created with Appsmith ! 

### Integrations and features
 - UI Design
 - Username, Password input fields
 - Buttons and text fields

#### Attachments
- [x] **Link to app** - Link to the _public_ app : [Link](https://app.appsmith.com/app/untitled-application-1/page1-6352946fdc264920d5e25e18)
- [x] **Screenshots** - Add one or more screenshots to help show your app.
![Screenshot (15)](https://user-images.githubusercontent.com/84070677/197202429-327bbc0c-87f5-4a44-ac1f-bec094255a96.png)

- [x] **JSON Export** - Attach the [JSON export](https://docs.appsmith.com/advanced-concepts/more/backup-restore#export-application) for your app to the issue. -> [Login Interface.zip](https://github.com/appsmithorg/foundry/files/9839208/Login.Interface.zip)

**Comment by rlnorthcutt** [comment]
Thank you for your submission. Unfortunately, you did not score high enough to win an award. But - please take part in our next event!
