### ISSUE TITLE
[TEMPLATE] simple loan calculator

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/foundry#17]
## Description
a simple loan calculator is a handy tool available online that enables you to calculate your EMI amount with much ease. the calculator will show you the interest amount earned for the loan tenure and the principal amount too.

### Integrations and features

You need to input three essential details in the simple loan calculator -
- principal amount
- time period
- rate of interest

#### Attachments
- [x] **Link to app** - [Link to the _public_ app](https://app.appsmith.com/app/simple-loan-calculator/simple-loan-calculator-6353896331cf9c0f4917e584)
- [x] **JSON Export** - [JSON Export](https://github.com/appsmithorg/foundry/files/9843817/simple.loan.calculator.json.zip)

##### Screenshots

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/4999463/197327518-5f63ca7a-1325-47b5-8902-6e9712f7d2c1.png">
<img width="1520" alt="image" src="https://user-images.githubusercontent.com/4999463/197327593-b4ef99dc-52a6-44a4-9fb0-28a4f3afb678.png">

**Comment by rlnorthcutt** [comment]
Congratulations! You won a bronze prize for this submission and 4 coins for use in the swag store!
