### ISSUE TITLE
[TEMPLATE] the standup app

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/foundry#18]
## Description
This app/template lets you document your thoughts at the start of each workday. Using this app gives teams an easy and quick peek into everyone's workload for the day, without time-consuming standups.

### Integrations and features
A list of specific integrations, data sources, and specific features
 - storeValue() function that stores key-value data to access later anywhere in the app
 - table with all recent checkins
 - a way to delete all the data
 - store checkins for a daily standup along with mood/feeling

#### Attachments
- [x] **Link to app** - [Link to the _public_ app](https://app.appsmith.com/app/the-standup-app/daily-standup-6353a1c431cf9c0f4917e62f)
- [x] **JSON Export** - Attach the [JSON export](https://github.com/appsmithorg/foundry/files/9844103/the.standup.app.json.zip)
- [x] **Inspiration** - Based on the request listed in [list of template requests](https://app.appsmith.com/app/request-templates/request-list-6241c12fc99df2369931a714) 

##### Screenshots

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/4999463/197334702-f82aaed6-a15f-4648-95f1-30a6201d00d5.png">
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/4999463/197334752-f160c01e-c8b0-4861-8698-b0569cdd5aa7.png">
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/4999463/197334720-2feed182-5ec8-4a0f-b3f7-75bb46429bb8.png">

**Comment by rlnorthcutt** [comment]
Thank you for your submission. Unfortunately, you did not score high enough to win an award. But - please take part in our next event!
