### ISSUE TITLE
[TEMPLATE] Login/Register/Forgot Password Form Variants

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/foundry#19]
## Description
Ultimate Logins is a set of two variants of form interfaces that include a login form, sign up form and a forgot password form. This template doesn't include any functionality but just shows how to call an alert from a JSON Object feature built in appsmith.

#### Attachments
- [x] **Link to app** - [Link to the _public_ app](https://app.appsmith.com/app/ultimate-logins/variant-1-register-63543f4631cf9c0f4917ee17)
- [x] **JSON Export** - [JSON export](https://github.com/appsmithorg/foundry/files/9845184/Ultimate.Logins.json.zip)
- [x] [Inspiration](https://app.appsmith.com/app/request-templates/request-list-6241c12fc99df2369931a714) 

##### Screenshots

![image](https://user-images.githubusercontent.com/4999463/197360253-1537d15d-40f4-497e-b157-76d5f815481f.png)
![image](https://user-images.githubusercontent.com/4999463/197360259-4f5a5f03-9a29-4b54-99ca-43fcd0726ede.png)
![image](https://user-images.githubusercontent.com/4999463/197360270-c875e349-2abd-4265-bd35-57fee2647537.png)
![image](https://user-images.githubusercontent.com/4999463/197360278-b4093133-307e-4db7-9afa-73ec030364db.png)
![image](https://user-images.githubusercontent.com/4999463/197360288-b9faf223-f81c-4e3f-b5dd-c292147524d6.png)
![image](https://user-images.githubusercontent.com/4999463/197360291-ebe45cec-6edd-4919-bc19-955973df4d71.png)

**Comment by rlnorthcutt** [comment]
Congratulations! You won a gold prize for this submission and 10 coins for use in the swag store!
