### ISSUE TITLE
[TEMPLATE] Character Count Tool using JS

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/foundry#20]
## Description
character count tool is an online tool that lets you easily calculate and count the number of characters, words, sentences, spaces and paragraphs in your text.

Also, learn how Javascript of how these are calculated to include in your code too!

### Integrations and features
 - simple JS code snippets to easily learn
 - auto clear persistent storage on page load
 - auto calculate counts when text changes using JS

#### Attachments
- [x] **Link to app** - [View App Live](https://app.appsmith.com/app/character-count-tool-using-js/counterpage-63550178dc264920d5e277b9)
- [x] **JSON Export** - [Download JSON Export](https://github.com/appsmithorg/foundry/files/9846822/Character.Count.Tool.using.JS.json.zip)
##### Screenshots

![image](https://user-images.githubusercontent.com/4999463/197399199-c7a81cb2-5e6e-4f46-9b11-0e0973b83f56.png)
![image](https://user-images.githubusercontent.com/4999463/197399211-a0fafc4a-eaa6-427c-8a17-63031296b029.png)
![image](https://user-images.githubusercontent.com/4999463/197399246-50914052-c592-477e-b5cf-1876724cf028.png)

**Comment by rlnorthcutt** [comment]
Congratulations! You won a silver prize for this submission and 7 coins for use in the swag store!
