### ISSUE TITLE
[TEMPLATE] Ecommerce 

### ISSUE THREAD

**Issue by sandeeprawat28** [appsmithorg/foundry#21]
## Description
.A E-commerce store template using appsmith

#### Attachments
- [ ] **Link to app** - [[Link to the _public_ app](https://app.appsmith.com/app/ecommerce-store/ecommerce-store-63565a92f6cdb970519c1019)]
- [ ] **Screenshots** - 
![Screenshot (49)](https://user-images.githubusercontent.com/76909857/197497923-48de8efe-cd7a-4c6f-8fa8-5ed748e1f7dd.png)
![Screenshot (50)](https://user-images.githubusercontent.com/76909857/197497958-0f789cb7-7415-49d9-9d98-102eb77c128e.png)

**Comment by rlnorthcutt** [comment]
This is a copy of a public template.
