### ISSUE TITLE
[TEMPLATE] Student Fees Dashboard

### ISSUE THREAD

**Issue by sanjus-robotic-studio** [appsmithorg/foundry#23]
## Description
A dashboard for school or educational management to manage the fees payment  of students

### Integrations and features
A list of specific integrations, data sources, and specific features
 - Mongo DB

#### Attachments
- [x] **Link to app** - https://app.appsmith.com/applications/6161501fea18372f051054d5/pages/6161501fea18372f051054d9
- [x] **JSON File** - [Student Database.zip](https://github.com/appsmithorg/foundry/files/9930385/Student.Database.zip)

**Comment by rlnorthcutt** [comment]
Great! Can you please attach a JSON export?
https://docs.appsmith.com/advanced-concepts/more/backup-restore#export-application

**Comment by sanjiv-anand** [comment]
@rlnorthcutt, I have made the changes

**Comment by rlnorthcutt** [comment]
Thank you for your submission. Unfortunately, you did not score high enough to win an award. But - please take part in our next event!
