### ISSUE TITLE
Google Maps Navigation

### ISSUE THREAD

**Issue by AyushSahu7477** [appsmithorg/foundry#24]
## Description
Guide your team with Google Maps directions, dynamically generated from your location or form a custom map pin added by the user.

### Integrations and features
A list of specific integrations, data sources, and specific features
 - PostgreSQL
 - RestAPI
 - mockDB

#### Attachments
- [ ] **Link to app** - [Link to the _public_ app](https://app.appsmith.com/app/google-maps-navigation/directions-6358003c0e05b60ea4e7f2ca)
- [ ] **Screenshots** - 
<img width="1440" alt="Screenshot 2022-10-25 at 9 03 11 PM" src="https://user-images.githubusercontent.com/115913356/197817702-ff2dd8b9-bcf3-45cd-9879-0e62c571f9c8.png">
<img width="1440" alt="Screenshot 2022-10-25 at 9 02 55 PM" src="https://user-images.githubusercontent.com/115913356/197817715-c2f293a6-cf09-41ac-bd25-cce7f48e9d31.png">
- [ ] **JSON Export** - [JSON-Export](https://drive.google.com/file/d/1KbXfsXn0O8PJDEHXTD8ZC9kqS7uVh_2B/view?usp=sharing)

**Comment by rlnorthcutt** [comment]
Copy of public template - doesn't count.
