### ISSUE TITLE
[TEMPLATE]  IT Asset Tracker

### ISSUE THREAD

**Issue by AyushSahu77** [appsmithorg/foundry#25]
## Description
Keep a track of an organization’s assets by assigning, and checking for any loss of assets or equipment, and ensure periodic maintenance.

### Integrations and features
A list of specific integrations, data sources, and specific features
 - PostgreSQL
 - API
 - asset tracker
 - google maps navigation

#### Attachments
- [ ] **Link to app** - [Link to the _public_ app](https://app.appsmith.com/app/it-asset-tracker/dashboard-63580667561dcd1ffe6d0d80)
- [ ] **Screenshots** - 
<img width="1440" alt="Screenshot 2022-10-25 at 9 27 38 PM" src="https://user-images.githubusercontent.com/102364606/197823308-222ea413-5ea3-4e4b-9761-16ef83977337.png">
<img width="1440" alt="Screenshot 2022-10-25 at 9 27 31 PM" src="https://user-images.githubusercontent.com/102364606/197823321-79129e52-8880-4516-8842-e5ab3d7e7f72.png">
<img width="1440" alt="Screenshot 2022-10-25 at 9 27 13 PM" src="https://user-images.githubusercontent.com/102364606/197823334-3429e04a-0b52-401f-8939-4700b07b9067.png">
- [ ] **JSON Export** - Attach the [JSON export](https://drive.google.com/file/d/1NmwcP2G05-saSQ6Jc_B48h04uzQWfaMY/view?usp=sharing) for your app to the issue.

**Comment by rlnorthcutt** [comment]
Copy of public app. Doesn't count for the contest.
