### ISSUE TITLE
[TEMPLATE] Quiz_a_Lang

### ISSUE THREAD

**Issue by CursedRock17** [appsmithorg/foundry#26]
## Description
This template application, Quiz_a_Lang, is a small quiz-based game that allows novice programmers to choose a language based on their preferences along with links to get started with the language. These links have been handpicked from the communities of each language so they can really get the best of the best.

### Integrations and features
A list of specific integrations, data sources, and specific features
- Appsmith.Store 

#### Attachments
- [x] **Link to app** [- Link to the _public_ app](https://app.appsmith.com/app/quiz-a-lang/page1-6356fb1df6cdb970519c1bf4)
- [x] **JSON Export** [- JSON_DATA](https://github.com/appsmithorg/foundry/files/9865527/quiz_a_lang.zip)
- [x] **Screenshots** <img width="1143" alt="No Image 1" src="https://user-images.githubusercontent.com/82680922/197920769-d6d20b48-16ef-475d-a9ee-2d84998061eb.png">
<img width="1152" alt="No Image 2" src="https://user-images.githubusercontent.com/82680922/197921113-a888434b-4d0b-413c-a214-7d58e243b98e.png">

**Comment by rlnorthcutt** [comment]
Not public, but able to use export to view.

**Comment by rlnorthcutt** [comment]
Thank you for your submission. Unfortunately, you did not score high enough to win an award. But - please take part in our next event!
