### ISSUE TITLE
[TEMPLATE] Kya Picture Dekhe? : An appsmith template app to connect to The Movie Database and view popular movies list.

### ISSUE THREAD

**Issue by AntiGhot** [appsmithorg/foundry#29]
## Description
An Appsmith App, that connects to The Movie Database using REST API, and displays the popular movie list.
Upon clicking a title, it shows you the keywords of that movie and movies similar to that movie, and helps you in taking a decision to watch it.

### Integrations and features
A list of specific integrations, data sources, and specific features
 - Datasource : Authenticated API
 - API :  The Movie Database REST API
 - Table
 - Modal
 - Image
 - Video
 - List
 - Button
 - Pages
 - JSObjects
 - appsmith.store
 - progress bar
 - iframe
 - container
 - actions

#### Attachments
- [x] **Link to app** - [Link to the _public_ app](https://app.appsmith.com/app/kya-picture-dekhe/home-6357e6310e05b60ea4e7f046?branch=main)
- [x] **Screenshots** - 
  - [screenshot_1](https://github.com/AntiGhot/kya-picture-dekhe/blob/main/screenshots/1.png)
  - [screenshot_2](https://github.com/AntiGhot/kya-picture-dekhe/blob/main/screenshots/2.png)
  - [screenshot_3](https://github.com/AntiGhot/kya-picture-dekhe/blob/main/screenshots/3.png)
  - [screenshot_4](https://github.com/AntiGhot/kya-picture-dekhe/blob/main/screenshots/4.png)
  - [screenshot_5](https://github.com/AntiGhot/kya-picture-dekhe/blob/main/screenshots/5.png)
  - [screenshot_6](https://github.com/AntiGhot/kya-picture-dekhe/blob/main/screenshots/6.png)
  - [screenshot_7](https://github.com/AntiGhot/kya-picture-dekhe/blob/main/screenshots/7.png)
  - [screenshot_8](https://github.com/AntiGhot/kya-picture-dekhe/blob/main/screenshots/8.png)
- [x] **JSON Export** - Attach the [JSON export](https://docs.appsmith.com/advanced-concepts/more/backup-restore#export-application) for your app to the issue.
Json attached as zip [Kya Picture Dekhe.zip](https://github.com/appsmithorg/foundry/files/9868342/Kya.Picture.Dekhe.zip)

**Comment by rlnorthcutt** [comment]
Congratulations! You won a silver prize for this submission and 7 coins for use in the swag store!
