### ISSUE TITLE
[TEMPLATE] Inventory Manager

### ISSUE THREAD

**Issue by bitbuit** [appsmithorg/foundry#34]
## Description
Inventory Manager helps your bussiness to control the stocks of every product in differents locations.

**Note:** It's a very simple implementation (developed for Hacktoberfest 2022) and some features are missing, but it's usable and beautiful :)

### Integrations and features
**Features**
 - Create locations
 - Create inventories
 - Add items
 - Edit items

**Integrations**
 - Postgres

#### Attachments
- [x] **Link to app** - [Inventory Manager](https://app.appsmith.com/app/inventory-manager/list-inventories-6337c73b75df0e6b2dda2bff)
- [x] **Screenshots** - Add one or more screenshots to help show your app.
![Inventory Manager 1](https://user-images.githubusercontent.com/10681878/198239699-c9bfda26-baa9-47ac-949f-f6b469713ab7.png)
![Inventory Manager 2](https://user-images.githubusercontent.com/10681878/198239709-8343239e-b1c4-47da-8fd2-25330c6cc448.png)
- [x] **JSON Export** - [Inventory manager template.zip](https://github.com/appsmithorg/foundry/files/9877790/Inventory.manager.template.zip)
- [x] **DB structure (SQL)** - [inventory-manager-db-sql.txt](https://github.com/appsmithorg/foundry/files/9877875/inventory-manager-db-sql.txt)

**Comment by rlnorthcutt** [comment]
Congratulations! You won a silver prize for this submission and 7 coins for use in the swag store!
