### ISSUE TITLE
[TEMPLATE] Track your Chess.com Players : An Appsmith App for Chess Enthusiast and Fans

### ISSUE THREAD

**Issue by amogh2019** [appsmithorg/foundry#38]
## Description
Track your Chess.com Players : An Appsmith App for Chess Enthusiast and Fans
It helps you keep a tab of the players you are looking to track.

Track Players Screen
- Shows player info (username, avatar, fullname, etc)
- Shows their recent games this month,
  - sorted by latest games first
  - with brief game info (who played, who was black/white, who won)
  - shows the link to detailed games screen
- Remove players from the list of players being track

Search Players Screen
- Show a list of titled players
- Filterable buttons for titled players list. Can filter to only see Grandmaster, Woman Grandmaster, etc other titles on Chess.com
- Add a titled player to your track list
- Search box to add any chess.com username to track
  - button to add as well as keyboard enter support.

### Integrations and features
A list of specific integrations, data sources, and specific features
 - Chess.com REST API
 - Tables
 - Filters in Tables
 - Promises
 - JSObject
 - List
 - Image
 - Text
 - Progress
 - Button
 - appsmith store
 - storeValue
 - switch
 - Pages
 - Input
 - moment js
 - Container

#### Attachments
- [x] **Link to app** - [Link to the _public_ app](https://app.appsmith.com/app/track-your-chess-com-players/search-players-635935170e05b60ea4e807fa?branch=main)
- [x] **Screenshots*
![1  homescreen](https://user-images.githubusercontent.com/56151951/198685825-1148b15f-66c8-49b3-a9ad-7a545f3b8860.png)
![2  filter GM](https://user-images.githubusercontent.com/56151951/198685831-c6965ee3-6b27-4453-8c99-f4b9a2faaa6b.png)
![3  alert on adding one of the GM player to track list](https://user-images.githubusercontent.com/56151951/198685832-0ef2be7e-1822-4e8b-8678-f654ad5569d5.png)
![4  success adding player using search box](https://user-images.githubusercontent.com/56151951/198685835-37fdf760-8c84-4e8f-9226-1201411f89d9.png)
![5  fail adding unknown player using search box](https://user-images.githubusercontent.com/56151951/198685839-d722518f-f6cb-4a12-abfe-396eb06d374c.png)
![6  track players screen - having list + details + games of the selected row player](https://user-images.githubusercontent.com/56151951/198685842-f81ef14b-8387-440c-92ab-400b4b4e0b9f.png)
![7  message when no games played in the current month](https://user-images.githubusercontent.com/56151951/198685843-18a15696-50ed-49cb-a441-3b0ead5ee165.png)
![8  updated list and track screen after removing a player](https://user-images.githubusercontent.com/56151951/198685844-1889a0b8-548a-4009-92b0-4656ba0922c3.png)
* - Add one or more screenshots to help show your app.

- [x] **JSON Export** - 
[Track your Chess Players.zip](https://github.com/appsmithorg/foundry/files/9890114/Track.your.Chess.Players.zip)

**Comment by rlnorthcutt** [comment]
Congratulations! You won a gold prize for this submission and 10 coins for use in the swag store!
