### ISSUE TITLE
[TEMPLATE] School Assets Tracker

### ISSUE THREAD

**Issue by samjacob16** [appsmithorg/foundry#39]
## Description
A clear dashboard to check which department have how many kinds of assets and also to request if any department wants more assets.

#### Attachments
- [ ] **Link to app** - https://app.appsmith.com/app/school-asset-tracker/dashboard-635d66cb2a523703d95f37f1
- [ ] **Screenshots** - Add one or more screenshots to help show your app.

**Comment by rlnorthcutt** [comment]
Hey @samjacob16 - this is a copy of a public template with a minor change. Unless there is some additional functionality I can not see, then this does not count for the contest.
