### ISSUE TITLE
Business Management Portal

### ISSUE THREAD

**Issue by Shivansh2030** [appsmithorg/foundry#41]
## Description
A simple portal to manage your business orders or sales on the go.

### Integrations and features
A list of specific integrations, data sources, and specific features
 - some DB
 - an API
Api used is of a company data you can inject your api and simply reflect the orders or business related things.

#### Attachments
- [x] **Link to app** - https://app.appsmith.com/app/business-portal/page1-635df5982a523703d95f3b9e
- [x] **Screenshots** - Add one or more screenshots to help show your app.
![business](https://user-images.githubusercontent.com/85742459/198864144-37477343-30aa-435f-b504-cd93d724cab4.png)
![business management](https://user-images.githubusercontent.com/85742459/198864146-ba887ffa-0b1c-452d-a9f3-f1dfd3de94f8.png

Thank you I hope you find my simple project useful 😊.

**Comment by rlnorthcutt** [comment]
Congratulations! You won a bronze prize for this submission and 4 coins for use in the swag store!
