### ISSUE TITLE
A simple Ecommerce Store

### ISSUE THREAD

**Issue by Shivansh2030** [appsmithorg/foundry#42]
## Description
A simple and normal representation of a ecommerce store. Appsmith helped too much to built this on a simple and nice portal.
### Integrations and features
A list of specific integrations, data sources, and specific features
 - some DB
 - an API
 - table with update modal

#### Attachments
- [ ] **Link to app** - https://app.appsmith.com/app/ecommerce-store/ecommerce-store-635e59010264ba459f174ddb
- [ ] **Screenshots** - 
![Screenshot_5](https://user-images.githubusercontent.com/85742459/198893548-0a3df573-3bd4-4a86-9459-3da34bcc48f2.png)

![Screenshot_4](https://user-images.githubusercontent.com/85742459/198893546-74f0cb78-8699-4487-a81d-72c212e21731.png)

- [ ] **JSON Export** - Attach the [JSON export](https://docs.appsmith.com/advanced-concepts/more/backup-restore#export-application) for your app to the issue.

**Comment by rlnorthcutt** [comment]
This is a clone of a public template with some color changes. Unless there is some functionality I am not aware of, this doesn't count for the contest.
