### ISSUE TITLE
[TEMPLATE] Skedule

### ISSUE THREAD

**Issue by darkbits018** [appsmithorg/foundry#43]
## Description
a simple schedulin app

### Integrations and features
A list of specific integrations, data sources, and specific features
 - some DB
 - an API
 - table with update modal

#### Attachments
- [ ] **Link to app** - https://app.appsmith.com/app/meeting-scheduler/calendar-mobile-635fb8302a523703d95f540e
- [ ] **Screenshots** - Add one or more screenshots to help show your app.
- [ ] **JSON Export** - Attach the [JSON export](https://docs.appsmith.com/advanced-concepts/more/backup-restore#export-application) for your app to the issue.

**Comment by rlnorthcutt** [comment]
Copy of a public template.
