### ISSUE TITLE
[TEMPLATE] Movies Panel

### ISSUE THREAD

**Issue by muezz** [appsmithorg/foundry#45]
## Description
This app is a dashboard for searching, filtering and analyzing movies.

### Integrations and features
 - Built-in Sample Movies Database in MongoDB
 - Gmail SMTP Integration
 - Carbone API Integration for Report Generation
 - Attach and send PDF files via Email
 - Loading Animation that hides individually loading widgets until all APIs have run.
 - Side Menu where the selected item is highlighted.
 - A Filter widget where the user can change the data shown in the dashboard.

#### Attachments
- [x] [**Link to App**](https://app.appsmith.com/app/movies-panel/home-6352565d4b1a8d4291235be1?embed=true)
- [x] **Screenshots**
![image](https://user-images.githubusercontent.com/100420605/199067976-63a906fa-1bf4-4b59-8984-1b5e880872f0.png)
![image](https://user-images.githubusercontent.com/100420605/199068492-859a6711-d250-4217-af54-189a479b116b.ng)
![image](https://user-images.githubusercontent.com/100420605/199068041-c02bc926-cdfb-4cc0-acf9-e03f05145a8f.png)
![image](https://user-images.githubusercontent.com/100420605/199068108-637af6ff-792d-409c-9d36-f811ddf95844.png)
![image](https://user-images.githubusercontent.com/100420605/199068267-38dd698d-962a-4d39-9358-951a4169e7f3.png)
![image](https://user-images.githubusercontent.com/100420605/199068355-fcc90526-2949-4955-aac8-ec479f0268ea.png)

- [x] **JSON Export**
[Movies Panel.zip](https://github.com/appsmithorg/foundry/files/9903356/Movies.Panel.zip)

**Comment by rlnorthcutt** [comment]
Congratulations! You won a gold prize for this submission and 10 coins for use in the swag store!
