### ISSUE TITLE
Meeting Scheduler

### ISSUE THREAD

**Issue by akarsh-jain-790** [appsmithorg/foundry#46]
## Description
Scheduling team meeting without the hassle of back and forth conversations is passe. With this app, you can let anyone set up and create meetings. All you have to do is authorize your Google Calendar and share the app with anyone you would like to. You can completely customize the duration of meetings and let your friends and colleagues know when they can reach you. You can also add in multiple visitors, and if you have a meeting URL, you can also add that.

Schedule Team Meetings without the Hassle of Back-and-Forth Emails.

### Integrations and features
A list of specific integrations, data sources, and specific features

- Users can create unlimited custom meeting durations
- Users can set their working hours on the settings page
- You can schedule meetings at any available time while maintaining privacy
- If you have a zoom account, you can add in meeting links, so no extra work is required
- You can customize the meeting text to attach your meeting ID without any integration required.

#### Attachments
- [x] **Link to app** - [Meeting Scheduler](https://app.appsmith.com/app/meeting-scheduler/calendar-mobile-63600c9e4939bd7a4807dee9)
- [x] **Screenshots** - Add one or more screenshots to help show your app.
- [x] **JSON Export** - Attach the [JSON export](https://docs.appsmith.com/advanced-concepts/more/backup-restore#export-application) for your app to the issue.

**Comment by GreenFlux** [comment]
Hi @akarsh-jain-790 , I'm getting a 'not found' error when trying to view this app. Could you please make sure it is set to public in the share settings?

**Comment by rlnorthcutt** [comment]
Not able to review - no public link, no screenshots, and no JSON export.
