### ISSUE TITLE
[TEMPLATE] Marketing Portal

### ISSUE THREAD

**Issue by tanishk-23** [appsmithorg/foundry#47]
## Description
A clear and concise description of what the template is and the use case it is intended to solve for.

### Integrations and features
A list of specific integrations, data sources, and specific features
 - some DB
 - an API
 - table with update modal

#### Attachments
- [ ] **Link to app** - https://app.appsmith.com/app/customer-communications-portal/send-messages-63600d504939bd7a4807df03
- [ ] **Screenshots** - Add one or more screenshots to help show your app.
- [ ] **JSON Export** - Attach the [JSON export](https://docs.appsmith.com/advanced-concepts/more/backup-restore#export-application) for your app to the issue.

**Comment by GreenFlux** [comment]
@tanishk-23 , I'm getting a 'not found' error when trying to view this app. Could you please make sure it is set to public in the share settings?

**Comment by rlnorthcutt** [comment]
Not able to review because it is not public.
