### ISSUE TITLE
[TEMPLATE] Calendly clone with stripe integration

### ISSUE THREAD

**Issue by sanjus-robotic-studio** [appsmithorg/foundry#6]
**Describe the template**
This App is the perfect clone of the Calendly app it has Stripe integration which makes the person who wants to have a meeting with the person needs to pay before he can schedule his meeting in the respective timing. The price for the meeting is set by the developer or the account user. This uses the meeting scheduler template from appsmith

**Link to the public app**
[Link](https://app.appsmith.com/app/meeting-scheduler-copy/calendar-mobile-62c052cf612750023eb08705)

**Integrations and features**
A list of specific integrations, data sources, and specific features
 - Google Calendar
 - Stripe API
 - Zoom API

**JSON File**
[Meeting Scheduler Copy.json.zip](https://github.com/appsmithorg/foundry/files/9930397/Meeting.Scheduler.Copy.json.zip)

**Screenshots**

![Screenshot 2022-10-16 at 11 45 43 AM](https://user-images.githubusercontent.com/58104863/196021182-e3b9dc50-e02a-4a39-888c-b6d7c219d582.png)

![Screenshot 2022-10-16 at 11 45 31 AM](https://user-images.githubusercontent.com/58104863/196021185-be1f56bc-311e-4bb6-aec2-fd7ea1adc2a3.png)
![Screenshot 2022-10-16 at 11 45 31 AM](https://user-images.githubusercontent.com/58104863/196021202-d00ab8e3-2d3d-45e5-83f1-261d0b7c4077.png)

**Comment by rlnorthcutt** [comment]
Hi! We need you to do two things, please:
1) Make the app publicly viewable (https://docs.appsmith.com/advanced-concepts/access-control#public-apps)
2) Export the JSON for the app and attach it as well (https://docs.appsmith.com/advanced-concepts/more/backup-restore#export-application)

**Comment by sanjiv-anand** [comment]
@rlnorthcutt I have made the changes

**Comment by rlnorthcutt** [comment]
Thank you for your submission. Unfortunately, you did not score high enough to win an award. But - please take part in our next event!
