### ISSUE TITLE
[TEMPLATE] Competition Online Application Generator with receipt Generation 

### ISSUE THREAD

**Issue by sanjus-robotic-studio** [appsmithorg/foundry#7]
**Describe the template**
This app provides a way for the Applicants to apply for the competition with their information from the list of contests after successful submission of the application, the applicant can print their receipt for the proof of submission.

**Link to the public app**
https://app.appsmith.com/app/vilampatti-summer-camp-registeration/homepage-62874b337901344ba8d10472

**Integrations and features**
A list of specific integrations, data sources, and specific features
 - Mongo DB
- Iframe widget for the printing

**JSON File**
[Vilampatti Summer Camp Registeration.json.zip](https://github.com/appsmithorg/foundry/files/9930351/Vilampatti.Summer.Camp.Registeration.json.zip)

**Comment by rlnorthcutt** [comment]
Hi! Can you export and attach the JSON for the app please?
https://docs.appsmith.com/advanced-concepts/more/backup-restore#export-application

**Comment by sanjiv-anand** [comment]
@rlnorthcutt Yes, Sure ! Added now !

**Comment by rlnorthcutt** [comment]
Thank you for your submission. Unfortunately, you did not score high enough to win an award. But - please take part in our next event!
