### ISSUE TITLE
[TEMPLATE] QR Code Generator and Verifier

### ISSUE THREAD

**Issue by sanjus-robotic-studio** [appsmithorg/foundry#8]
**Describe the template**
This app generates QR code and lets the users to verify the code by scanning on it. 

**Link to the public app**
[Link](https://app.appsmith.com/app/qr-code-generator/qr-code-generator-634bce11c99f19072638d614)

**Integrations and features**
A list of specific integrations, data sources, and specific features
 -QR code Generation API
 -QR Code Scanner 

**JSON File**
[QR Code Generator.zip](https://github.com/appsmithorg/foundry/files/9930412/QR.Code.Generator.zip)

**Screenshots**

![Screenshot 2022-10-16 at 5 26 53 PM](https://user-images.githubusercontent.com/58104863/196034134-2ccdefa6-2278-4f93-b1d9-eb6738a7ab41.png)

![Screenshot 2022-10-16 at 5 26 32 PM](https://user-images.githubusercontent.com/58104863/196034132-74cee26a-4e71-466c-bf31-94afcac492e8.png)

**Comment by rlnorthcutt** [comment]
Hi - the app seems to be blank. Perhaps you need to deploy your changes or update your public app link?

Also, can you export and attach the JSON for the app: https://docs.appsmith.com/advanced-concepts/more/backup-restore#export-application

**Comment by sanjiv-anand** [comment]
@rlnorthcutt, I have made the changes

**Comment by rlnorthcutt** [comment]
Congratulations! You won a gold prize for this submission and 10 coins for use in the swag store!
